version: 0.0
os: linux
files:
  - source: /target/*.jar
    destination: /home/ubuntu/app/
permissions:
  - object: /home/ubuntu/app/
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_server
      timeout: 300
      runas: ubuntu
