name: Java CI with Maven

on: [ push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies
      run: mvn install -DskipTests
    - name: Compile
      run: mvn compile
    - name: Scan with PMD
      run: mvn pmd:check
    - name: Scan with SpotBugs
      run: mvn spotbugs:check
    - name: Scan with CheckStyle
      run: mvn checkstyle:check
  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Package
      run: mvn package -DskipTests
    - name: Compress
      run: tar -czf $GITHUB_SHA.tar.gz appspec.yml target/*.jar scripts/*
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-northeast-2'
    - name: upload to AWS S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://$PROJECT_NAME/$GITHUB_SHA.tar.gz
    - name: tag object
      run: |
        aws s3 put-object-tagging --bucket gs-testing-web --key $GITHUB_SHA.tar.gz --tagging '{ "TagSet": [{ "Key": "Deploy", "Value": "True" }] }'
