name: Java CI with Maven

on: [ push, pull_request]
jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Scan with PMD
      run: mvn pmd:check
  spotbugs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Scan with SpotBugs
      run: mvn spotbugs:check
  checkstyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Scan with CheckStyle
      run: mvn checkstyle:check
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit Test
      run: mvn test
  deploy:
    needs: [ pmd, spotbugs, checkstyle, test ]
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Package
      run: mvn package -DskipTests
    - name: Compress
      run: tar -czf $GITHUB_SHA.tar.gz appspec.yml target/*.jar scripts/*
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-northeast-2'
    - name: upload to AWS S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://gs-testing-web/$GITHUB_SHA.tar.gz
    - name: execute CodeDeploy
      run: aws deploy create-deployment --application-name gs-testing-web --deployment-group-name ec2 --s3-location bucket=gs-testing-web,key=$GITHUB_SHA.tar.gz,bundleType=tgz
